# Project Name
TARGET = Sequencer

# Sources
CPP_SOURCES = main.cpp

# Library Locations
LIBDAISY_DIR = ../../ModuleDev/DaisyExamples/libDaisy/
DAISYSP_DIR = ../../ModuleDev/DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
